x-environment: &db-environment
  - POSTGRES_USER=fcsc2022
  - POSTGRES_PASSWORD=fcsc2022
  - POSTGRES_DB=fcsc2022
  - POSTGRES_HOST=cloud-password-manager-db
  - PUBLIC_URL=http://cloud-password-manager-www:${PORT}/

services:
  cloud-password-manager-www:
    image: anssi/fcsc2022-web-cloud-password-manager-www:latest
    ports:
      - ${PORT}:8000
    environment: *db-environment
    networks:
      - cloud-password-manager-external
      - cloud-password-manager-internal

  cloud-password-manager-db:
    image: anssi/fcsc2022-web-cloud-password-manager-db:latest
    environment: *db-environment
    networks:
      - cloud-password-manager-internal

  cloud-password-manager-bot:
    image: anssi/fcsc2022-web-cloud-password-manager-bot:latest
    environment: *db-environment
    networks:
      - cloud-password-manager-external
      - cloud-password-manager-internal

networks:
  cloud-password-manager-external:
  cloud-password-manager-internal:
    internal: true
